USE [master]
GO
/****** Object:  Database [outlet]    Script Date: 15-Feb-17 10:23:56 PM ******/
CREATE DATABASE [outlet]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'outlet', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\outlet.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'outlet_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\outlet_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [outlet] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [outlet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [outlet] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [outlet] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [outlet] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [outlet] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [outlet] SET ARITHABORT OFF 
GO
ALTER DATABASE [outlet] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [outlet] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [outlet] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [outlet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [outlet] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [outlet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [outlet] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [outlet] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [outlet] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [outlet] SET  DISABLE_BROKER 
GO
ALTER DATABASE [outlet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [outlet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [outlet] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [outlet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [outlet] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [outlet] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [outlet] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [outlet] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [outlet] SET  MULTI_USER 
GO
ALTER DATABASE [outlet] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [outlet] SET DB_CHAINING OFF 
GO
ALTER DATABASE [outlet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [outlet] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [outlet] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [outlet] SET QUERY_STORE = OFF
GO
USE [outlet]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [outlet]
GO
/****** Object:  Table [dbo].[products]    Script Date: 15-Feb-17 10:23:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[products](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NULL,
	[manufacturer] [varchar](50) NULL,
	[price] [numeric](18, 0) NULL,
	[description] [varchar](50) NULL,
	[imageName] [varchar](50) NULL,
	[isNew] [bit] NULL,
 CONSTRAINT [PK_products] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[users]    Script Date: 15-Feb-17 10:23:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[login] [varchar](50) NULL,
	[password_hash] [varchar](250) NULL,
	[email] [varchar](50) NULL,
	[created] [date] NULL,
	[role] [varchar](50) NULL,
 CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [outlet] SET  READ_WRITE 
GO
